---
- name: Rename nodes (with handlers)
  hosts: all
  become: True
  tasks:
      
  - name: Set a hostname
    ansible.builtin.hostname:
        name: "{{ name }}"    
    tags: Set
    notify: restart the node


        
#  - name: Wait for the node to come back
#    ansible.builtin.wait_for_connection:
#        delay: 60
#        timeout: 300

  - name: verify the hostname
    ansible.builtin.command:
        cmd: hostname
    register: result
    tags: show

  - name: print the hostname from linux command
    ansible.builtin.debug:
        var: result.stdout
    tags: show
  
  - name: Print the hostname in facts
    ansible.builtin.debug:
        msg: "The value in facts is: {{ ansible_facts['nodename'] }}"
    tags: show

  
  - name: Use the template
    ansible.builtin.template:
      src: etchosts.j2
      dest: /etc/hosts
      backup: true
      owner: root
      group: root
      mode: '0644'
    tags: Set
        
  handlers:
  - name: restart the node
    ansible.builtin.reboot: