---
- name: Block rescue
  hosts: all

  vars:
    failure_on: "web"

  tasks:
   - name: Handle the error
     block:
       - name: Print a message
         ansible.builtin.debug:
           msg: 'I execute normally'

       - name: Force a failure on {{failure_on}}
         ansible.builtin.command: /bin/false
         when: "failure_on in group_names"

       - name: Never print this
         ansible.builtin.debug:
           msg: 'I never execute on {{failure_on}}, due to the above task failing, :-('

     rescue:
       - name: Print when errors
         ansible.builtin.debug:
           msg: 'I caught an error on {{group_names}}, can do stuff here to fix it, :-)'
